// Code generated by "stringer -type=Perm"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PERM_READ-1]
	_ = x[PERM_WRITE-2]
	_ = x[PERM_EXEC-4]
	_ = x[PERM_RAW-8]
}

const (
	_Perm_name_0 = "PERM_READPERM_WRITE"
	_Perm_name_1 = "PERM_EXEC"
	_Perm_name_2 = "PERM_RAW"
)

var (
	_Perm_index_0 = [...]uint8{0, 9, 19}
)

func (i Perm) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Perm_name_0[_Perm_index_0[i]:_Perm_index_0[i+1]]
	case i == 4:
		return _Perm_name_1
	case i == 8:
		return _Perm_name_2
	default:
		return "Perm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
